### ISSUE TITLE
theme: change license (simple case)

### ISSUE THREAD

**Issue by switowski** [inveniosoftware/invenio-theme#115]

**Comment by switowski** [comment]
Problematic packages:
- [ ] pytest-cache 1.0	 --> GNU General Public License (GPL):
  - This one is strange - if you check the source code on bitbucket: https://bitbucket.org/hpk42/pytest-cache/overview you see that in the `setup.py` it specifies the `MIT` license, but if you install the package and do `pip show --verbose pytest-cache`, you can find `License :: OSI Approved :: GNU General Public License (GPL)` as one of the classifiers. Anyway, according to the note on the bitbucket page, pytest-cache is part of pytest core from `pytest-2.8.0`, so I think we can remove it from the `setup.py`?
- [ ] chardet 3.0.4 (`Sphinx` is installing `requests>=2.0.0` that is installing `chardet`)	 --> LGPL
- [ ] docutils 0.14 (dependency of `Sphinx`)	 --> public domain, Python, 2-Clause BSD, GPL 3 (see COPYING.txt):
  - There are 2 files inside docutils that are under GPL, but I don't think we use them?:
    * tools/editors/emacs/tests/ert-buffer.el
    * tools/editors/emacs/rst.el

**Comment by lnielsen** [comment]
LGPL is fine

**Comment by lnielsen** [comment]
Closed by #117
