### ISSUE TITLE
Overriding the theme logo doesn't work

### ISSUE THREAD

**Issue by GeoSpark** [inveniosoftware/invenio-theme#133]
In an Invenio 3.1 application, the blueprint is set up such that its static_folder is set to 'static'. But adding a logo file to `<app>/theme/static/` and setting THEME_LOGO doesn't find the logo file because invenio-theme's `templates/invenio_theme/header.html` has:

`<a href="/"><img class="navbar-brand" src="{{ url_for('static', filename=config.THEME_LOGO) }}" alt="{{ _(config.THEME_SITENAME) }}"/></a>`

Where the `url_for()` call uses 'static' which finds only the theme's static folder, not our custom one.

Overriding the `brand` block doesn't work because `invenio_theme/frontpage.html` `include`s `invenio_theme/header_frontpage.html` and Jinja2 doesn't support overriding blocks in included files.

One solution of course is to use something like Nginx to serve static files, but it would be nice to have this work in the development server.

**Comment by lnielsen** [comment]
Can you try this one: https://github.com/inveniosoftware/training/tree/master/05-customizing-invenio using latest cookiecutter (in particular you need this [commit](https://github.com/inveniosoftware/cookiecutter-invenio-instance/commit/1562eda612781c4755c15cee2808399fbb05f124))
