### ISSUE TITLE
docs: write a bootstrap 3 to semantic ui migration guide

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-theme#148]
First ideas:
https://codimd.web.cern.ch/bfDyh_ejQJSq-DZpGCSfMA

**Comment by ppanero** [comment]
Did one roundcheck. Corrected/added some things to the codimd. Seems good to me, though some parts could be ordered different to make it more user friendly (I have some thoughts if someone takes this ping me).

**Comment by ppanero** [comment]
Ready to be reviewed: https://codimd.web.cern.ch/e1xbBZ2fSviRGJ0_Xuiv6w 🎊
