### ISSUE TITLE
styles: semantic-ui hr footer line extends too long on search page

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-theme#162]
The footer line (see screenshot) extends edge to edge the search result page, compared to eg. frontpage. 

![Screenshot 2020-05-18 at 10 30 32](https://user-images.githubusercontent.com/1698163/82191966-97d4c500-98f3-11ea-985a-7ceb03058f3d.png)

Expected:

![Screenshot 2020-05-18 at 10 39 28](https://user-images.githubusercontent.com/1698163/82192137-db2f3380-98f3-11ea-825c-387b32649a05.png)

**Comment by zzacharo** [comment]
@lnielsen I couldn't reproduce this in my RDM instance...Both search page and frontpage templates have the divider from edge to edge and the "Powered by Invenio" left aligned. Can you give me some more explanation on how should the footer look like?

**Comment by lnielsen** [comment]
Verified that it's fixed in latest cookiecutter
