### ISSUE TITLE
semantic-ui: login box footer should not have bottom border

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-theme#165]
![Screenshot 2020-05-18 at 10 44 13](https://user-images.githubusercontent.com/1698163/82192734-ac658d00-98f4-11ea-8475-8b2abdfdb2a2.png)

The grey line highlighted in the screenshot should be same color as above

**Comment by zzacharo** [comment]
Closing in favour of https://github.com/inveniosoftware/invenio-accounts/issues/327
