### ISSUE TITLE
semantic-ui: reset password modal is missing spacing

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-theme#166]
![Screenshot 2020-05-18 at 10 47 28](https://user-images.githubusercontent.com/1698163/82193034-1aaa4f80-98f5-11ea-94c6-eac5eebd9b58.png)

Compared to boostrap:

![image](https://user-images.githubusercontent.com/1698163/82193045-20a03080-98f5-11ea-819d-c78885e77686.png)

**Comment by zzacharo** [comment]
@lnielsen is this what we need? I copy pasted the margin from https://zenodo.org/lost-password/

<img width="563" alt="Screenshot 2020-06-17 at 18 37 44" src="https://user-images.githubusercontent.com/22594783/84925115-c0ee9e00-b0c9-11ea-92ed-c45ec5b995ea.png">
