### ISSUE TITLE
styles: header not centered

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-theme#195]
.... or content not centered:

![Screenshot 2020-06-30 at 08 25 43](https://user-images.githubusercontent.com/6756943/89273142-70aea980-d63f-11ea-860b-fe92d7486239.png)

![Screenshot 2020-06-30 at 08 24 33](https://user-images.githubusercontent.com/6756943/89273152-73a99a00-d63f-11ea-9e5d-10f6ed04884b.png)

**Comment by jrcastro2** [comment]
closed by https://github.com/inveniosoftware/invenio-theme/pull/198 and https://github.com/inveniosoftware/invenio-theme/pull/199
