### ISSUE TITLE
Community logo gets replaced by placeholder

### ISSUE THREAD

**Issue by jennur** [inveniosoftware/invenio-theme#301]
The community logo gets replaced by the placeholder even though the logo is available.

See https://github.com/inveniosoftware/invenio-theme/blob/master/invenio_theme/assets/semantic-ui/js/invenio_theme/theme.js#L20 

Note: `.has-placeholder` was removed from all images to prevent this bug.

**Comment by ntarocco** [comment]
@jennur this requires a chain of releases, right?
