### ISSUE TITLE
docs: update structure

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio-theme#56]
- introduce new documentation structure https://github.com/inveniosoftware/cookiecutter-invenio-module/issues/56
- document user perspective
- document signals (if not done)
- document example app (if not done)

**Comment by lnielsen** [comment]
Document:
- [ ] example application (what is the app demonstrating - the templates, error pages, menu, ...)
- [ ] configuration (in particular ``BASE_TEMPLATE``, ...)
- [ ] usage guide:
   - [ ] menu/breadcrumb system and endpoints.
   - [ ] default bundles and what they provide
   - [ ] templates and their blocks + macros


End-user perspective:
- What does the module provide, and how do I make simple changes (e.g. change logo etc).
